export default {
  PRODUCTS_FETCH_START: "PRODUCTS_FETCH_START",
  PRODUCTS_FETCH_SUCCESS: "PRODUCTS_FETCH_SUCCESS",
  PRODUCTS_FETCH_ERROR: "PRODUCTS_FETCH_ERROR",
  PRODUCTS_DETELE_ONE: "PRODUCTS_DETELE_ONE",
  PRODUCTS_DETELE_ONE_SUCCESS: "PRODUCTS_DETELE_SUCCESS",
  PRODUCTS_DETELE_ONE_ERROR: "PRODUCTS_DETELE_ERROR",
  PRODUCTS_ADD: "PRODUCTS_ADD",
  PRODUCTS_ADD_SUCCESS: "PRODUCTS_ADD_SUCCESS",
  PRODUCTS_ADD_ERROR: "PRODUCTS_ADD_ERROR",
  PRODUCTS_UPDATE: "PRODUCTS_UPDATE",
  PRODUCTS_UPDATE_SUCCESS: "PRODUCTS_UPDATE_SUCCESS",
  PRODUCTS_UPDATE_ERROR: "PRODUCTS_UPDATE_ERROR",
};
